// This file will be auto-generated by Supabase CLI
// For now, defining basic types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          user_id: string;
          created_at: string;
          risk_score: number;
          is_banned: boolean;
          updated_at: string;
          email?: string | null;
        };
        Insert: {
          user_id: string;
          created_at?: string;
          risk_score?: number;
          is_banned?: boolean;
          updated_at?: string;
          email?: string | null;
        };
        Update: {
          user_id?: string;
          created_at?: string;
          risk_score?: number;
          is_banned?: boolean;
          updated_at?: string;
          email?: string | null;
        };
        Relationships: [];
      };
      admins: {
        Row: {
          user_id: string;
          created_at: string;
        };
        Insert: {
          user_id: string;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      devices: {
        Row: {
          id: string;
          user_id: string;
          device_hash: string;
          ip_hash: string;
          first_seen_at: string;
          last_seen_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          device_hash: string;
          ip_hash: string;
          first_seen_at?: string;
          last_seen_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          device_hash?: string;
          ip_hash?: string;
          first_seen_at?: string;
          last_seen_at?: string;
        };
        Relationships: [];
      };
      user_ip_logs: {
        Row: {
          id: number;
          user_id: string;
          event: string;
          ip: string | null;
          user_agent: string | null;
          path: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          user_id: string;
          event: string;
          ip?: string | null;
          user_agent?: string | null;
          path?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          user_id?: string;
          event?: string;
          ip?: string | null;
          user_agent?: string | null;
          path?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      presence_heartbeats: {
        Row: {
          user_id: string;
          last_seen: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          last_seen?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          last_seen?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      points_ledger: {
        Row: {
          id: string;
          user_id: string;
          delta: number;
          type: string;
          reason: string;
          ref_type: string | null;
          ref_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          delta: number;
          type: 'credit' | 'debit';
          reason: string;
          ref_type?: string | null;
          ref_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          delta?: number;
          type?: 'credit' | 'debit';
          reason?: string;
          ref_type?: string | null;
          ref_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      rewards: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          points_cost: number;
          stock: number;
          status: 'active' | 'inactive' | 'out_of_stock';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          points_cost: number;
          stock?: number;
          status?: 'active' | 'inactive' | 'out_of_stock';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          points_cost?: number;
          stock?: number;
          status?: 'active' | 'inactive' | 'out_of_stock';
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      redemptions: {
        Row: {
          id: string;
          user_id: string;
          reward_id: string;
          points_spent: number;
          status: 'pending' | 'fulfilled' | 'rejected';
          created_at: string;
          admin_note?: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          reward_id: string;
          points_spent: number;
          status?: 'pending' | 'fulfilled' | 'rejected';
          created_at?: string;
          admin_note?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          reward_id?: string;
          points_spent?: number;
          status?: 'pending' | 'fulfilled' | 'rejected';
          created_at?: string;
          admin_note?: string | null;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: string;
          actor: string;
          action: string;
          target_type: string | null;
          target_id: string | null;
          payload: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor: string;
          action: string;
          target_type?: string | null;
          target_id?: string | null;
          payload?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          actor?: string;
          action?: string;
          target_type?: string | null;
          target_id?: string | null;
          payload?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      offerwall_events: {
        Row: {
          id: string;
          provider: string;
          user_id: string | null;
          transaction_id: string | null;
          status: string | null;
          reward_points: number | null;
          payout_tl: number | null;
          raw_payload: Json;
          created_at: string;
          credited_at: string | null;
        };
        Insert: {
          id?: string;
          provider: string;
          user_id?: string | null;
          transaction_id?: string | null;
          status?: string | null;
          reward_points?: number | null;
          payout_tl?: number | null;
          raw_payload: Json;
          created_at?: string;
          credited_at?: string | null;
        };
        Update: {
          id?: string;
          provider?: string;
          user_id?: string | null;
          transaction_id?: string | null;
          status?: string | null;
          reward_points?: number | null;
          payout_tl?: number | null;
          raw_payload?: Json;
          created_at?: string;
          credited_at?: string | null;
        };
        Relationships: [];
      };
      offer_conversions: {
        Row: {
          id: string;
          provider: string;
          user_id: string;
          transaction_id: string;
          offer_id: string | null;
          reward_points: number;
          raw_payload: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          provider: string;
          user_id: string;
          transaction_id: string;
          offer_id?: string | null;
          reward_points: number;
          raw_payload?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          provider?: string;
          user_id?: string;
          transaction_id?: string;
          offer_id?: string | null;
          reward_points?: number;
          raw_payload?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      offer_completions: {
        Row: {
          id: string;
          provider: string;
          event_id: string;
          user_id: string;
          reward_points: number;
          raw_payload: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          provider: string;
          event_id: string;
          user_id: string;
          reward_points: number;
          raw_payload?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          provider?: string;
          event_id?: string;
          user_id?: string;
          reward_points?: number;
          raw_payload?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      referrals: {
        Row: {
          referrer_user_id: string;
          referred_user_id: string;
          bonus_awarded: boolean;
          created_at: string;
        };
        Insert: {
          referrer_user_id: string;
          referred_user_id: string;
          bonus_awarded?: boolean;
          created_at?: string;
        };
        Update: {
          referrer_user_id?: string;
          referred_user_id?: string;
          bonus_awarded?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      get_user_points: {
        Args: { p_user_id: string };
        Returns: number;
      };
      get_all_users_points: {
        Args: Record<string, never>;
        Returns: { user_id: string; total_points: number | string; last_activity: string | null }[];
      };
      redeem_reward: {
        Args: { p_user_id: string; p_reward_id: string | number };
        Returns: { success: boolean; error?: string; redemption_id?: string; points_spent?: number; new_points?: number; reward_title?: string } | null;
      };
      credit_offerwall_event: {
        Args: {
          p_event_id: string;
          p_credit_enabled: boolean;
          p_test_allowlist?: string[];
        };
        Returns: { success: boolean; error?: string; skipped?: string; credited?: boolean; user_id?: string; points?: number; provider?: string } | null;
      };
    };
    Enums: Record<string, never>;
  };
}
