// This file will be auto-generated by Supabase CLI
// For now, defining basic types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          user_id: string;
          created_at: string;
          risk_score: number;
          is_banned: boolean;
          updated_at: string;
          email?: string | null;
        };
        Insert: {
          user_id: string;
          created_at?: string;
          risk_score?: number;
          is_banned?: boolean;
          updated_at?: string;
          email?: string | null;
        };
        Update: {
          user_id?: string;
          created_at?: string;
          risk_score?: number;
          is_banned?: boolean;
          updated_at?: string;
          email?: string | null;
        };
        Relationships: [];
      };
      admins: {
        Row: {
          user_id: string;
          created_at: string;
        };
        Insert: {
          user_id: string;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      devices: {
        Row: {
          id: string;
          user_id: string;
          device_hash: string;
          ip_hash: string;
          first_seen_at: string;
          last_seen_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          device_hash: string;
          ip_hash: string;
          first_seen_at?: string;
          last_seen_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          device_hash?: string;
          ip_hash?: string;
          first_seen_at?: string;
          last_seen_at?: string;
        };
        Relationships: [];
      };
      user_ip_logs: {
        Row: {
          id: string;
          user_id: string | null;
          ip: string;
          user_agent: string | null;
          path: string | null;
          event: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          ip: string;
          user_agent?: string | null;
          path?: string | null;
          event: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          ip?: string;
          user_agent?: string | null;
          path?: string | null;
          event?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      presence_heartbeats: {
        Row: {
          user_id: string;
          last_seen: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          last_seen?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          last_seen?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      points_ledger: {
        Row: {
          id: string;
          user_id: string;
          delta: number;
          type: string;
          reason: string;
          ref_type: string | null;
          ref_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          delta: number;
          type: 'credit' | 'debit';
          reason: string;
          ref_type?: string | null;
          ref_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          delta?: number;
          type?: 'credit' | 'debit';
          reason?: string;
          ref_type?: string | null;
          ref_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      rewards: {
        Row: {
          id: string;
          title: string;
          provider: string;
          kind: string;
          image_url: string | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          provider?: string;
          kind?: string;
          image_url?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          provider?: string;
          kind?: string;
          image_url?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      reward_variants: {
        Row: {
          id: string;
          reward_id: string;
          denomination_tl: number;
          cost_points: number;
          stock: number | null;
          daily_limit_per_user: number | null;
          min_account_age_days: number | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          reward_id: string;
          denomination_tl: number;
          cost_points: number;
          stock?: number | null;
          daily_limit_per_user?: number | null;
          min_account_age_days?: number | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          reward_id?: string;
          denomination_tl?: number;
          cost_points?: number;
          stock?: number | null;
          daily_limit_per_user?: number | null;
          min_account_age_days?: number | null;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      reward_redemptions: {
        Row: {
          id: string;
          user_id: string;
          variant_id: string;
          cost_points: number;
          payout_tl: number;
          status: string;
          idempotency_key: string;
          note: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          variant_id: string;
          cost_points: number;
          payout_tl: number;
          status?: string;
          idempotency_key: string;
          note?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          variant_id?: string;
          cost_points?: number;
          payout_tl?: number;
          status?: string;
          idempotency_key?: string;
          note?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      tb_reward_redemptions: {
        Row: {
          id: string;
          user_id: string;
          variant_id: string;
          cost_points: number;
          payout_tl: number;
          status: string;
          idempotency_key: string;
          note: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          variant_id: string;
          cost_points: number;
          payout_tl: number;
          status?: string;
          idempotency_key: string;
          note?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          variant_id?: string;
          cost_points?: number;
          payout_tl?: number;
          status?: string;
          idempotency_key?: string;
          note?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      admin_actions: {
        Row: {
          id: string;
          actor_id: string | null;
          action: string;
          target_type: string | null;
          target_id: string | null;
          meta: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_id?: string | null;
          action: string;
          target_type?: string | null;
          target_id?: string | null;
          meta?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          actor_id?: string | null;
          action?: string;
          target_type?: string | null;
          target_id?: string | null;
          meta?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      tb_security_events: {
        Row: {
          id: string;
          user_id: string | null;
          event_type: string;
          ip: string;
          user_agent: string;
          device_fingerprint: string | null;
          country: string | null;
          created_at: string;
          metadata: Json;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          event_type: string;
          ip: string;
          user_agent?: string;
          device_fingerprint?: string | null;
          country?: string | null;
          created_at?: string;
          metadata?: Json;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          event_type?: string;
          ip?: string;
          user_agent?: string;
          device_fingerprint?: string | null;
          country?: string | null;
          created_at?: string;
          metadata?: Json;
        };
        Relationships: [];
      };
      tb_risk_assessments: {
        Row: {
          id: string;
          entity_type: string;
          entity_id: string;
          user_id: string;
          risk_score: number;
          flags: string[];
          recommended_action: string;
          details: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          entity_type: string;
          entity_id: string;
          user_id: string;
          risk_score: number;
          flags?: string[];
          recommended_action: string;
          details?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          entity_type?: string;
          entity_id?: string;
          user_id?: string;
          risk_score?: number;
          flags?: string[];
          recommended_action?: string;
          details?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      tb_admin_audit_log: {
        Row: {
          id: string;
          admin_user_id: string;
          action: string;
          entity_type: string | null;
          entity_id: string | null;
          before_state: Json | null;
          after_state: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          admin_user_id: string;
          action: string;
          entity_type?: string | null;
          entity_id?: string | null;
          before_state?: Json | null;
          after_state?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          admin_user_id?: string;
          action?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          before_state?: Json | null;
          after_state?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      tb_fulfillment_jobs: {
        Row: {
          id: string;
          redemption_id: string;
          status: string;
          attempts: number;
          last_error: string | null;
          next_run_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          redemption_id: string;
          status?: string;
          attempts?: number;
          last_error?: string | null;
          next_run_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          redemption_id?: string;
          status?: string;
          attempts?: number;
          last_error?: string | null;
          next_run_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: string;
          actor: string;
          action: string;
          target_type: string | null;
          target_id: string | null;
          payload: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor: string;
          action: string;
          target_type?: string | null;
          target_id?: string | null;
          payload?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          actor?: string;
          action?: string;
          target_type?: string | null;
          target_id?: string | null;
          payload?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      offerwall_events: {
        Row: {
          id: string;
          provider: string;
          user_id: string | null;
          transaction_id: string | null;
          status: string | null;
          reward_points: number | null;
          payout_tl: number | null;
          raw_payload: Json;
          created_at: string;
          credited_at: string | null;
        };
        Insert: {
          id?: string;
          provider: string;
          user_id?: string | null;
          transaction_id?: string | null;
          status?: string | null;
          reward_points?: number | null;
          payout_tl?: number | null;
          raw_payload: Json;
          created_at?: string;
          credited_at?: string | null;
        };
        Update: {
          id?: string;
          provider?: string;
          user_id?: string | null;
          transaction_id?: string | null;
          status?: string | null;
          reward_points?: number | null;
          payout_tl?: number | null;
          raw_payload?: Json;
          created_at?: string;
          credited_at?: string | null;
        };
        Relationships: [];
      };
      offer_conversions: {
        Row: {
          id: string;
          provider: string;
          user_id: string;
          transaction_id: string;
          offer_id: string | null;
          reward_points: number;
          raw_payload: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          provider: string;
          user_id: string;
          transaction_id: string;
          offer_id?: string | null;
          reward_points: number;
          raw_payload?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          provider?: string;
          user_id?: string;
          transaction_id?: string;
          offer_id?: string | null;
          reward_points?: number;
          raw_payload?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      offer_completions: {
        Row: {
          id: string;
          provider: string;
          event_id: string;
          user_id: string;
          reward_points: number;
          raw_payload: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          provider: string;
          event_id: string;
          user_id: string;
          reward_points: number;
          raw_payload?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          provider?: string;
          event_id?: string;
          user_id?: string;
          reward_points?: number;
          raw_payload?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      referrals: {
        Row: {
          referrer_user_id: string;
          referred_user_id: string;
          bonus_awarded: boolean;
          created_at: string;
        };
        Insert: {
          referrer_user_id: string;
          referred_user_id: string;
          bonus_awarded?: boolean;
          created_at?: string;
        };
        Update: {
          referrer_user_id?: string;
          referred_user_id?: string;
          bonus_awarded?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      get_user_points: {
        Args: { p_user_id: string };
        Returns: number;
      };
      get_all_users_points: {
        Args: Record<string, never>;
        Returns: { user_id: string; total_points: number | string; last_activity: string | null }[];
      };
      redeem_reward: {
        Args: { p_variant_id: string; p_idempotency_key: string; p_note?: string | null };
        Returns: {
          success: boolean;
          error?: string;
          message?: string;
          redemption_id?: string;
          status?: string;
          cost_points?: number;
          payout_tl?: number;
          idempotent?: boolean;
        } | null;
      };
      credit_offerwall_event: {
        Args: {
          p_event_id: string;
          p_credit_enabled: boolean;
          p_test_allowlist?: string[];
        };
        Returns: { success: boolean; error?: string; skipped?: string; credited?: boolean; user_id?: string; points?: number; provider?: string } | null;
      };
    };
    Enums: Record<string, never>;
  };
}
